# Generated by Django 3.2.6 on 2021-09-14 01:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('config', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='clubentries',
            old_name='club_id',
            new_name='club',
        ),
        migrations.RenameField(
            model_name='clubentries',
            old_name='profile_id',
            new_name='profile',
        ),
        migrations.RenameField(
            model_name='profiledates',
            old_name='club_id',
            new_name='club',
        ),
        migrations.RenameField(
            model_name='profiledates',
            old_name='date_id',
            new_name='date',
        ),
        migrations.RenameField(
            model_name='profiledates',
            old_name='profile_id',
            new_name='profile',
        ),
        migrations.RenameField(
            model_name='profiles',
            old_name='user_id',
            new_name='user',
        ),
    ]
