# Generated by Django 3.2.6 on 2021-09-17 12:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('config', '0002_auto_20210914_0115'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dates',
            name='day',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='dates',
            name='hour',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='dates',
            name='minute',
            field=models.IntegerField(),
        ),
    ]
