# Generated by Django 3.2.6 on 2021-09-17 12:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('config', '0003_auto_20210917_1205'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profiledates',
            name='club',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='config.clubs'),
        ),
    ]
