# Generated by Django 3.2.6 on 2021-09-21 08:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('config', '0004_alter_profiledates_club'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='clubentries',
            options={'verbose_name': 'Club entrie'},
        ),
        migrations.AlterModelOptions(
            name='clubs',
            options={'verbose_name': 'Club'},
        ),
        migrations.AlterModelOptions(
            name='dates',
            options={'verbose_name': 'Date'},
        ),
        migrations.AlterModelOptions(
            name='profiledates',
            options={'verbose_name': 'Profile date'},
        ),
        migrations.AlterModelOptions(
            name='profiles',
            options={'verbose_name': 'Profile'},
        ),
    ]
