# Generated by Django 3.2.6 on 2021-10-20 04:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('config', '0005_auto_20210921_0807'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='dates',
            name='hour',
        ),
        migrations.RemoveField(
            model_name='dates',
            name='minute',
        ),
        migrations.AddField(
            model_name='dates',
            name='end_hours',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='dates',
            name='end_minutes',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='dates',
            name='starting_hours',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='dates',
            name='starting_minutes',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='dates',
            name='day',
            field=models.IntegerField(default=0),
        ),
    ]
