# Generated by Django 3.2.6 on 2021-11-09 04:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('config', '0006_auto_20211020_0425'),
    ]

    operations = [
        migrations.AddField(
            model_name='profiles',
            name='nickname',
            field=models.CharField(default='', max_length=100),
        ),
    ]
