# Generated by Django 3.2.6 on 2021-11-09 05:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('config', '0007_profiles_nickname'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profiles',
            name='nickname',
        ),
    ]
