# Generated by Django 3.2.6 on 2021-11-14 08:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('config', '0008_remove_profiles_nickname'),
    ]

    operations = [
        migrations.AddField(
            model_name='clubs',
            name='color',
            field=models.CharField(default='#FFFFFF', max_length=100),
        ),
    ]
