# Generated by Django 3.2.6 on 2021-11-23 01:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('config', '0009_clubs_color'),
    ]

    operations = [
        migrations.CreateModel(
            name='ClubSnapshots',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_date', models.DateTimeField(auto_now_add=True)),
                ('club', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='config.clubs')),
            ],
        ),
        migrations.AddField(
            model_name='profiledates',
            name='snapshot',
            field=models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='config.clubsnapshots'),
        ),
    ]
