# Generated by Django 3.2.9 on 2021-11-28 02:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('config', '0011_auto_20211128_0133'),
    ]

    operations = [
        migrations.RenameField(
            model_name='clubs',
            old_name='end_hour',
            new_name='end_hours',
        ),
        migrations.RenameField(
            model_name='clubs',
            old_name='starting_hour',
            new_name='starting_hours',
        ),
    ]
