# Generated by Django 3.2.9 on 2021-12-01 12:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('config', '0013_auto_20211201_1224'),
    ]

    operations = [
        migrations.RenameField(
            model_name='profiledatestosnapshot',
            old_name='profile_dates',
            new_name='profile_date',
        ),
    ]
